org: dsaltarin
app: serverapp
service: serverapp
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  productos:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: post
      - httpApi:
          path: /
          method: get
    layers:
      - arn:aws:lambda:us-east-1:011725170319:layer:sqlalchemy:2
